version: '3.9'

services:
    database:
        container_name: ptii_database
        image: postgres
        volumes:
            - database:/var/lib/postgresql/data/
        environment:
            - POSTGRES_NAME=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=database
            - POSTGRES_PORT=${POSTGRES_PORT}
        ports:
            - 5432:5432

    web:
        container_name: ptii_web
        build:
            context: .
            dockerfile: Dockerfile
        volumes:
            - .:/code
        ports:
            - '8000:8000'
        environment:
            - POSTGRES_NAME=${POSTGRES_NAME}
            - POSTGRES_USER=${POSTGRES_USER}
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_HOST=database
            - POSTGRES_PORT=${POSTGRES_PORT}
        depends_on:
            - database
        command: bash -c "python manage.py migrate && python manage.py runserver 0.0.0.0:8000"

volumes:
    database:
