name: CI PTI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest

    steps: 
    - uses: actions/checkout@v3
    - name: Setup env variables
      run: |
        touch .env
        echo POSTGRES_NAME=${{ secrets.POSTGRES_NAME }} >> .env
        echo POSTGRES_USER=${{ secrets.POSTGRES_USER }} >> .env
        echo POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }} >> .env
        echo POSTGRES_PORT=${{ secrets.POSTGRES_PORT }} >> .env
            
    - name: Build docker image
      run: docker-compose build
    
    - name: Up containers
      run: docker-compose up -d
      
    - name: Teste
      run: docker exec -i ptii_web pytest core/tests/integration/data/repositories/test_subcategory.py 
